name: Deploy dziro_bot_order

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo "== Переключаемся в проект =="
            cd ~/dziro_bot_order || exit 1

            echo "== Обновляем код =="
            git pull

            echo "== Собираем образ =="
            sudo docker-compose build

            echo "== Останавливаем старый контейнер =="
            sudo docker-compose down || true

            echo "== Запускаем бот (foreground) =="
            sudo docker-compose up -d

            echo "== Проверяем статус =="
            sleep 3
            sudo docker ps --format 'table {{.Names}}\t{{.Status}}'

            echo "== Чистим мусор =="
            sudo docker system prune -af --volumes
